### ISSUE TITLE
Error scaling nii.img when differs in data type to slope and inter

### ISSUE THREAD

**Issue by aot** [xiangruili/dicm2nii#10]
I also posted this on the matlab file exchange page.  I've encountered a bug when trying to load some enhanced dicom philips data (using 20181102) :

Error using * 
Integers can only be combined with integers of the same class, or scalar doubles.

Error in dicm2nii>set_nii_hdr (line 1237) 
nii.img = nii.img * slope + inter; % apply to img if no rounding

Error in dicm2nii (line 879) 
[nii, h{i}] = set_nii_hdr(nii, h{i}, pf); % set most nii hdr

Error in dicm2nii>gui_callback (line 1733) 
dicm2nii(src, dst, rstFmt);

I've set a break point at line 1237 in dicm2nii.m, here nii.img is int16, slope and inter are both floats (slope = 1, inter = 0), which is why it complains. That line is in the following condition:

```
if isa(nii.img, 'float') || (mod(slope,1)==0 && mod(inter,1)==0 ... 
&& val(1)>=intmin(dClass) && val(2)<=intmax(dClass)) 
nii.img = nii.img * slope + inter; % apply to img if no rounding 
else
```

perhaps the best thing to do here is to cast slope and inter to the same class as nii.img. Given that there are checks they the values are integers anyway this shouldn't lead to a loss in precision?

I actually tried this out and was able to successfully convert the data (question is, is this now correct!).  

` niiImgClass = class(nii.img); % AOT 181105 determine class of nii.img, cast inter and slope to this
        nii.img = nii.img * cast(slope, niiImgClass) + cast(inter, niiImgClass); % apply to img if no rounding`

**Comment by xiangruili** [comment]
The error is due to that Philips `MRScaleSlope` is in 'single' precision. Line 1237 won't complain if both `slope` and `inter` are in `double` precision. The latest commit should fix the problem. Thank you for reporting.
