### ISSUE TITLE
Inconsistent slice spacing for Subject. Series skipped.  No valid series found

### ISSUE THREAD

**Issue by Youguang** [xiangruili/dicm2nii#11]
The dicm2nii ver20181102 show this error while ver20180116 can convert successfully.

**Comment by xiangruili** [comment]
@Youguang 
The code for slice spacing check seems unchanged since 201801. Would you mind to share the dataset giving the problem?

**Comment by Youguang** [comment]
@xiangruili 

Here is the data I shared from onedrive:
https://1drv.ms/u/s!AkbzfRwwkjgziOFz1UO98-ygE8Oo7w

Thank you.

**Comment by xiangruili** [comment]
@Youguang 
Thank you for the testing data. It is due to a bug in dicm_hdr.m. The latest commit should fix it.

**Comment by Youguang** [comment]
@xiangruili 
Thank you for solving this problem so quickly.

**Comment by xiangruili** [comment]
@Youguang 
You don't need to re-convert. Even if you re-convert, the output will be the same. 
I am going to close this issue. Thank you for reporting and providing testing data.
