### ISSUE TITLE
hdr/img to nii

### ISSUE THREAD

**Issue by Student-HXJ** [xiangruili/dicm2nii#16]
Hi,  is there a script could convert two files (.hdr/.img) to single file (.nii), could you list a example.   Thank you in advance.

**Comment by xiangruili** [comment]
You can use `nii_tool.m` to do it easily. It is included in the package.

    nii = nii_tool('load', 'myHdrFolder/run1.hdr'); % load hdr/img files
    nii_tool('save', nii, 'myNiiFolder/run1.nii'); % save it as nii file. Add `.gz` in the name for compression

You can do `doc nii_tool` for more syntax help if needed.

You can close this issue after you see the solution.

**Comment by Student-HXJ** [comment]
Thank you very much

**Comment by Student-HXJ** [comment]
Sorry, I got a problem. 
When I use nii_tool('save',....)
I got an error about One or more output arguments not assigned during call to "varargout".

**Comment by xiangruili** [comment]
I guess you requested output for nii_tool('save', ...), something like 

    out = nii_tool('save', ...) 

The next update will avoid this error even if you do this. For now, do not request any output for 'save' command.

**Comment by Student-HXJ** [comment]
But I didn't request any output for nii_tool('save',...)
I did totally follow your example code.
```
nii = nii_tool('load', 'myHdrFolder/run1.hdr'); 
nii_tool('save', nii, 'myNiiFolder/run1.nii'); 
```
Then I got the error.

**Comment by xiangruili** [comment]
That sounds strange. A possibility is that you might have implicitly requested output, something like 

    nii_tool('save', nii, 'myNiiFolder/run1.nii') + 1;

Anyway, I just updated the `save` part, trying to avoid the error by returning useless empty. Give it a try.

Thanks.

**Comment by Student-HXJ** [comment]
Sorry, where I can get the updated file?
the nii_tool.m is still committed 13days ago.
