### ISSUE TITLE
Fieldmap dual magnitude issue

### ISSUE THREAD

**Issue by orchid666** [xiangruili/dicm2nii#17]
Thanks a lot for this really cool toolbox, it works great!
Although I still have an issue with fieldmap. Two magnitude sequences are being acquired with different TE but within one run. They should be separated but dicm2nii treat them as one, and end up creating one .nii file and one json file. 
Is there a way to create both files? 

Thanks !

**Comment by xiangruili** [comment]
The converter tries to create one nii file from one dicom "series".  That is why those two volume are in one nii file. 

The second volume seems useless to me. I know it won't affect FSL if you have the extra second volume. Does it affect other packages?

In very early version of the converter, I simply dropped the second volume. But later I thought it is better to keep all data, and users can choose to drop anything as needed.

You can simply remove the second volume by

    nii = nii_tool('load', 'myFilePath/myFieldmap.nii.gz'); % load the 2-volume nii
    nii.img = nii.img(:,:,:,2); % take first volume only
    nii_tool('save', nii, 'myFilePath/fieldmap_volume_1.nii.gz') % save volume 1 only

In case you want to save another nii for volume 2, you can do it similarly.

**Comment by orchid666** [comment]
Thanks a lot for the quick reply, I actually need both magnitude file, as I use them for Fieldmap correction with fmriprep.  I'll take your advice to separate them post-conversion.
