### ISSUE TITLE
How is slice timing calculated?

### ISSUE THREAD

**Issue by orchid666** [xiangruili/dicm2nii#18]
I noticed that dicm2nii was able to give the SliceTiming tag in the json file for my data. However, a toll like dcm2niix is not able to do that, because my data was acquired with A25 software circa 2004 (syngo_MR_2004A_4VA25A). The tag MosaicRefAcqTimes is therefore not present in the dicom header. I tried to look at the code, but could not figure out how slice timing was calculated in the absence of that information. Thanks!

**Comment by xiangruili** [comment]
If you look into the sub-fuction `sliceTiming()` inside `dicm2nii.m`, you will see the converter first tries `MosaicRefAcqTimes`. If it is not available, other methods are tried, like `ucMode` in the CSA series header. I guess that is where the information was collected for your data.
