### ISSUE TITLE
PAR-REC conversion to NII using dicm2nii

### ISSUE THREAD

**Issue by shilpitju** [xiangruili/dicm2nii#27]
Hi,

I tried using the tool for the PAR-REC to NII conversion. I gave PAR file as the input but got the following error:
>> dicm2nii
Validating 1 files ...
 No valid files found:

not enough input arguments

Please guide me how to sort this out.

Regards,

Shilpi

**Comment by xiangruili** [comment]
If you have the REC file together with the PAR file, the likely reason is that the `dicm_hdr` could not read the PAR file correctly, or the PAR file corrupted. Please try following with your PAR file, and provide the outcome:

    [s, err] = dicm_hdr('/myFolder/myFile.PAR')

The err may provide the reason for failure.

**Comment by shilpitju** [comment]
Hi,

I ran [s, err] = dicm_hdr('/myFolder/myFile.PAR') and got the following error:

s =

     []


err =

    'not enough input arguments'

**Comment by xiangruili** [comment]
@shilpitju 
That error info is not helpful. Would you mind to share the PAR file? You can attach file here (drag&drop) or send me to xiangrui.li at gmail.com.

**Comment by shilpitju** [comment]
Please check your inbox.

**Comment by xiangruili** [comment]
@shilpitju 
Are you using the latest version? The two files works for me without problem.

**Comment by shilpitju** [comment]
I again downloaded from here:
https://github.com/xiangruili/dicm2nii

Still facing the same issue.

**Comment by xiangruili** [comment]
@shilpitju 
When you run dicm2nii first time, it will show version (date format), like

    Xiangrui Li's dicm2nii.m 20200112 (feedback to xiangrui.li at gmail.com)

What is it?

**Comment by shilpitju** [comment]
The version is:
Xiangrui Li's dicm2nii.m 20200112

**Comment by xiangruili** [comment]
The path setting may not be right on your computer. Could you try this again?

    [s, err] = dicm_hdr('/myFolder/myFile.PAR')  % change to your folder and file name

If it still gives error, please check following two point to the same folder:

    which dicm2nii
    which dicm_hdr

**Comment by shilpitju** [comment]
Sorry to trouble you again, but 
[s, err] = dicm_hdr('/myFolder/myFile.PAR')  % change to your folder and file name
still gave error.

>> which dicm2nii
C:\Users\sxm684\Downloads\dicm2nii-master\dicm2nii-master\dicm2nii.m
>> which dicm_hdr
C:\Users\sxm684\Downloads\dicm2nii-master\dicm2nii-master\dicm_hdr.m

**Comment by xiangruili** [comment]
The path looks good, supposing dicm2nii gives you version 20200112.

Are you sure these two file you sent to me are the files with problem? dicm_hdr reads them well on my test:

    Sub_01_fMRI_SENSE_9_1.PAR
    Sub_02_Task_SENSE_11_1.PAR

**Comment by neurolabusc** [comment]
@shilpitju as a wild guess, are you using Windows, Linux or MacOS, and what is the full path to your files. I do know  some tools have problems with unusual path names, for example Slicer has issues with Chinese characters or umlauts in file names, and different operating systems have different [special characters](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md).

**Comment by shilpitju** [comment]
@neurolabusc Path for the input PAR files (also sent to @xiangruili) is:
C:\Users\sxm684\Desktop\Test\Sub_01 and 
C:\Users\sxm684\Desktop\Test\Sub_02

**Comment by shilpitju** [comment]
@xiangruili 
1. I downloaded dicm2nii and set path of MATLAB to the path of the dicm2nii-master folder
2. typing dicm2nii on MATLAB command window and hitting enter
3. GUI settings of dicm2nii
![Input](https://user-images.githubusercontent.com/57184150/72451820-87b4a980-378a-11ea-9c6e-080a2307aab8.png)

4. The MATLAB output
![Output](https://user-images.githubusercontent.com/57184150/72451821-87b4a980-378a-11ea-8396-e2a80874874d.png)

**Comment by xiangruili** [comment]
@shilpitju  That is really strange. Can you try following from Matlab command line?

    dicm2nii('C:\Users\sxm684\Desktop\Test\Sub_01', 'C:\Users\sxm684\Desktop\Test\Sub_01')

After you get the "not enough input arguments" error, find the error by

    lasterror

And post the screen output.

**Comment by shilpitju** [comment]
![Error](https://user-images.githubusercontent.com/57184150/72470905-9f525900-37af-11ea-8f10-4fb250dee296.png)

**Comment by xiangruili** [comment]
@shilpitju  Could you save the variable 'me' and attach the file here or my email, as shown in my above message?

**Comment by shilpitju** [comment]
[myErrorFile.zip](https://github.com/xiangruili/dicm2nii/files/4067655/myErrorFile.zip)

**Comment by xiangruili** [comment]
Sorry that is a different error:

```
me = 
  struct with fields:
       message: 'The class internal.deviceplugindetection.VNTDevicePluginDetectionClient has no Constant property or Static method named 'deviceRemovalHandler'.'
    identifier: 'MATLAB:subscripting:classHasNoPropertyOrMethod'
         stack: [6×1 struct]
```

Please run 
````
dicm2nii('C:\Users\sxm684\Desktop\Test\Sub_01', 'C:\Users\sxm684\Desktop\Test\Sub_01')
````
or
````
[s, err] = dicm_hdr('/myFolder/myFile.PAR')  % change to your folder and file name
````
After you get the error, do 
````
save myErrorFile me; % attach the file here
````

**Comment by xiangruili** [comment]
@shilpitju Also it does not sound right if you have only one file. You should have at least a pair of PAR/REC file for the conversion to work.

**Comment by shilpitju** [comment]
> @shilpitju Also it does not sound right if you have only one file. You should have at least a pair of PAR/REC file for the conversion to work.

Actually, it was giving errors every-time so I tried various permutations and combinations (by deleting REC file). However, the error is still there when REC file is in the folder.

**Comment by shilpitju** [comment]
> save myErrorFile me; % attach the file here

![Me_error](https://user-images.githubusercontent.com/57184150/72534729-4af9b880-3845-11ea-8f60-eb0874f7cce6.png)

**Comment by shilpitju** [comment]
[myErrorFile.zip](https://github.com/xiangruili/dicm2nii/files/4071848/myErrorFile.zip)

**Comment by xiangruili** [comment]
It seems you put the REC file together with PAR. Unfortunately that takes over the last error. Could you remove the REC file, so the "not enough input arguments" will be the last error for us to catch?

```
dicm2nii('C:\Users\sxm684\Desktop\Test\Sub_01', 'C:\Users\sxm684\Desktop\Test\Sub_01')
me = lasterror
save myErrorFile me; % attach the file here
```

Make sure "not enough input arguments" is the error.

**Comment by shilpitju** [comment]
After removing the REC file from the folder, I get the following:

![Me_error_latest](https://user-images.githubusercontent.com/57184150/72552729-886e3e00-3865-11ea-9941-5127350c72eb.png)

**Comment by shilpitju** [comment]
[myErrorFile.zip](https://github.com/xiangruili/dicm2nii/files/4073128/myErrorFile.zip)

**Comment by xiangruili** [comment]
I am sorry, but the error message seems from your previous try with GUI, not the latter command line. If you still like to debug, I would suggest the following approach, and hope we can find the culprit. 

First, run following from Matlab Command Window:
````
dbstop if error % will stop in code if error
````
Second, try to read the PAR with dicm_hdr:
````
[s, err] = dicm_hdr('C:\Users\sxm684\Desktop\Test\Sub_01\Sub_01_fMRI_SENSE_9_1.PAR');
````
If the expected "not enough input arguments" happens, Matlab will open the file with error, and the cursor will stay at the line giving the error. If the error is in dicm_hdr.m, go to Matlab Command Window, and save the variables in the debug mode:
````
me = lasterror
save myErrorFile; % attach the file here or to my email
````
If the error points to a file other than dicm_hdr.m, you can ````edit dicm_hdr````, and find an arrow next to a line number. That is the line giving error. You may take a screenshot for the Editor with the arrow. Also do the above ````lasterror```` and ````save```` lines.

**Comment by shilpitju** [comment]
'Matlab will open the file with error, and the cursor will stay at the line giving the error.' - Nothing of this sort happened. err, me and s were created.

![Me_error_new](https://user-images.githubusercontent.com/57184150/72557305-780e9100-386e-11ea-94d4-40aa1467f985.png)

**Comment by shilpitju** [comment]
The MyErrorFile now created is attached.
[myErrorFile.zip](https://github.com/xiangruili/dicm2nii/files/4073430/myErrorFile.zip)

**Comment by xiangruili** [comment]
As you can see from ````me```` output, it is for a USB audio device (do you have one connected to your computer and it is running something at background?). 

Anyway the "not enough input arguments" error was not captured. Now I extracted function philips_par.m from dicm_hdr.m, and is attaching here.
[philips_par.zip](https://github.com/xiangruili/dicm2nii/files/4073955/philips_par.zip)

You can unzip philips_par.m into the same folder as dicm_hdr.m, and run the following:
````
dbstop if error 
s = philips_par('C:\Users\sxm684\Desktop\Test\Sub_01\Sub_01_fMRI_SENSE_9_1.PAR');
````
After you get error and the code stops in philips_par, run following from command window:
````
me = lasterror
save myErrorFile; % attach the file here or to my email
````
Make sure the error is not USB related stuff.

**Comment by shilpitju** [comment]
I hope it works this time...sorry for troubling you....The screen shot is as:

![philips_par](https://user-images.githubusercontent.com/57184150/72638034-87eea980-3930-11ea-8126-330fc73393b0.png)

**Comment by shilpitju** [comment]
Here's the file:
[myErrorFile.zip](https://github.com/xiangruili/dicm2nii/files/4078409/myErrorFile.zip)

**Comment by xiangruili** [comment]
Hooray, we identified the problematic file!

As you can see in the screenshot you posted, the error happens in function ````makehgtform````. That is a function from Matlab. But as shown in your picture, matlab narginchk is overshadowed. So I guess ````makehgtform```` is also overshadowed by a function from spm12, and it may be buggy.

You can check this by 
````
which makehgtform
````
and see where it points. If indeed it points to somewhere in spm12, the simple solution is to delete that file.

**Comment by xiangruili** [comment]
@shilpitju 
It is updated. You can update your dicm2nii package from `dicm2nii` or `nii_viewer` GUI easily.
You can close this issue if it is fixed. Thanks.

**Comment by shilpitju** [comment]
Ohh...that's a fantastic news....that means, I will have to download dicm2nii thereafter.

Thanks so much for your help and effort.

**Comment by shilpitju** [comment]
Thanks again very much. Its working fine now.
