### ISSUE TITLE
Conversion on Debian 10 creates invalid Nifti files

### ISSUE THREAD

**Issue by takn20** [xiangruili/dicm2nii#29]
Hi! 

I have been using dicm2nii with Lead DBS for 1.5 years and am really happy with it. Thank you for your work! Now I am moving from Windows 7 to Debian 10 (Lead DBS 2.3, Matlab 2019b). On Debian using dicm2nii converts the Dicoms to Niftis without an error, but Lead DBS cannot use them afterwards. 

Trying to load the Niftis to mricron gives the error, "Illegal Nifti format header: this header does not specify 1..7 dimensions." 
Trying to convert the Dicoms with dcm2niix from Lead DBS gives the error, "corrupt DICOM images".
Going back to Windows (Matlab 2016b, Lead DBS 2.2.3) with dicm2nii converts the Dicom to Niftis without error and I can use them in Lead DBS on the Debian machine (mricron also displays them normally). 

Is this some file or line ending encoding?

Thanks for your help and let me know if you need more info.

**Comment by xiangruili** [comment]
Are you saying the same convertible dicom under Windows has problem to convert under Debian 10? If so, it sounds an OS problem somewhere. Could you please reproduce a small NIfTI file with the problem and attach it here?

**Comment by takn20** [comment]
Thank you for your prompt reply. The output from Matlab is:
`[str, ~, endian] = computer
str =
    'GLNXA64'
endian =
    'L'`

Yes, so I was able to convert the DICOM under Windows, but under Debian 10 it created invalid NIfTI files. This morning I had the DICOM images anonymized and wanted to send you a corrupt NIfTI, but then this morning it worked without a problem on two patient sets. I still have some corrupt NIfTI files, but they are not anonymized, so I am not allowed to send these.

I need to investigate further. Let's close the issue for now and I may reopen it, if you are ok with it.

Thank again.
