### ISSUE TITLE
character conversion in PAR file names

### ISSUE THREAD

**Issue by julienbesle** [xiangruili/dicm2nii#3]
I'm not sure if this is a bug or a feature, but spaces and underscores in the file names of PAR files get converted to underscores and hyphens respectively. For instance 
testJulien_COR-T1W_3D_TFE SENSE_7_2.PAR
gets converted into 
testJulien_COR_T1W_3D_TFE_SENSE_7_2.nii.gz

I think converting spaces to underscores is fine, as spaces in file names can be problematic, but I think underscores should remain underscores..

**Comment by neurolabusc** [comment]
For dcm2niix I used [this](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) and [this](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) page to identify forbidden characters. On needs to watch how special characters (e.g. German umlauts). Be aware that DICOM only supports UTF-8 encoding for Unicode, which can impact many languages. 

As a simple example, one of the files you shared with us included the line
`Examination name                   :   G/6/2009`
and if you use this for the output filename you will have issues (e.g. with dcm2niix appending the 'comment', ` -f %c_%s` ) you will have real problems.

**Comment by xiangruili** [comment]
@julienbesle , it is my intention to use underscore to replace any characters invalid for matlab variable name. For file names, it is better to keep minus sign as it is, but I use the same file name as matlab struct fieldname to store dicom (or others) hdr in dcmHeaders.mat, so choose to replace any unusual char with underscore.

**Comment by julienbesle** [comment]
Hi Xiangruili,

I meant to add that I don't think it's a good idea to modify characters in file names unless these are illegal in filenames, as described by Chris. I wouldn't change legal characters like underscores, or even spaces, for the convenience of using the filename as a field in a maltab structure, because this is not the behaviour most users would except.
One thing you could do instead is changing the name internally according to set rules (as you describe above), but keep the original name in memory for writing the file out.
In any case, it's up to you how want to do this.
Cheers
