### ISSUE TITLE
Creating a release to enable automatic downloading of dicm2nii 

### ISSUE THREAD

**Issue by jsheunis** [xiangruili/dicm2nii#32]
Hi @xiangruili 

Thanks for a great toolbox! I'm using it currently to read, view and write fMRI NIfTI images. It was the first toolbox I came across that helped me solve image orientation inconsistencies that drove me crazy previously :D.

I am now setting up an online environment to allow others to reproduce my code and results and would like to automatically download `dicm2nii` for use in this environment. Would you be able to create a release of the code base on github? This would create a compressed and downloadable file, which would make things on my side much easier.

Best,

Stephan

**Comment by xiangruili** [comment]
@jsheunis 
I believe you can simply use `git` command to download the package:

    git clone https://github.com/xiangruili/dicm2nii.git

The above command will create dicm2nii folder under your current folder. This is the system command solution, and you can call it within Matlab:

    system('git clone https://github.com/xiangruili/dicm2nii.git');

If, for some reason, you don't have `git` and don't want to install it, you can check the `checkUpdate()` sub-function within `dicm2nii.m`. It is called by `dicm2nii` and `nii_viewer` GUI to update the package. 

Let me know if you need further information. Thanks.

**Comment by jsheunis** [comment]
Thanks for the quick response.

Sorry, I could probably have been clearer about what exactly I'd like to do. I'm setting up a Jupyter notebook with an Octave kernel that I want to run on [Binder](https://mybinder.org/). You can look at the basic setup that I have [here](https://github.com/jsheunis/spm12-octave-jupyter).

In order to use `dicm2nii` with this setup, I need to include a shell command that Binder will run to download and install `dicm2nii`automatically each time it serves the code and data. I have currently solved it by forking your github repo and creating a release of it myself (see [here](https://github.com/jsheunis/dicm2nii/releases)). This allows me to include the shell command for Binder:

```
curl -SL https://github.com/jsheunis/dicm2nii/archive/v0.1.tar.gz | tar -xzC ${HOME}/dicm2nii --strip-components 1
```

I would prefer that my setup downloads the code base directly from the source, i.e. your repo. But I am happy with my solution if you'd prefer not to do that.

**Comment by xiangruili** [comment]
I am sorry I did not get what you want. It seems you have much more git experience than I do :)
Would the following zip file work for your purpose?
    https://github.com/xiangruili/dicm2nii/archive/master.zip

**Comment by jsheunis** [comment]
That works, thanks! I didn't even know one can download a branch like that via url :)
