### ISSUE TITLE
dicm2nii broken in last version

### ISSUE THREAD

**Issue by tanguyduval** [xiangruili/dicm2nii#33]
Hi @xiangruili 

A user reported to me a broken converter after update at this line: dicm2nii.m Line: 619 Column: 37
I guess in a recent update you used a notation that is not compatible with older version of Matlab. I would suggest to change to this:
`AcquisitionDate = {[acq{1}(1:4) '-' acq{1}(5:6) '-' acq{1}(7:8)]};`

Best

**Comment by xiangruili** [comment]
@tanguyduval 
There was a post at Matlab Central for the error there, so I corrected by using string. I thought that part supports only later Matlab anyway, so I used string (since R2016b). 
I just corrected it as you suggest. Thanks.
