### ISSUE TITLE
String & char differs

### ISSUE THREAD

**Issue by Haoxin22** [xiangruili/dicm2nii#34]
Hi Xiangrui,

Thank you for your excellent work!

I notice one tiny issue some people might face in the future. I think the input of path is not robust to string and seems like by default it only accepts char.

E.g.:
Source_Folder_Path = "my/path/to/the/folder"   -> error
Source_Folder_Path = 'my/path/to/the/folder'     -> OK

Hope this will help you make the package even better :)

**Comment by xiangruili** [comment]
Thank you for raising the issue, @Haoxin22 .
The Matlab string object has been there for years, and it is about time to take care of the compatibility. 
The latest update tries to make string acceptable for multiple function. This looks a trivial change, and it may cause some minor issues.
