### ISSUE TITLE
CSASeriesHeaderInfo

### ISSUE THREAD

**Issue by rstobbe** [xiangruili/dicm2nii#35]
In dicm_dict, Siemens 'Private_0029_1020' and 'Private_0029_1120' are both mapped to 'CSASeriesHeaderInfo'.  It is the Private_0029_1020 field that contains useful information, but in the dcmHeader.mat file created, CSASeriesHeaderInfo contains the info from Private_0029_1120.

**Comment by xiangruili** [comment]
I thought 'Private_0029_1020' and 'Private_0029_1120' are different versions used by Siemens. Did you mean both of them appear in a dicom file? If so, we need to name them differently, so both will be kept. Would you mind to share a dicom with me?

**Comment by filip-szczepankiewicz** [comment]
Indeed, both tags appear in the Edmonton dicom header. Unfortunately I cannot share data at this point. Most data I have worked with has the proper CSA in 0029_1120, but for some reason the Edmonton site used to have it there but it moved to 0029_1020.

As you say, an easy fix is to give them different names and deal with the fact that similar fields are present in the output structure. Please let me know if I can help you with this!

/F

**Comment by xiangruili** [comment]
@filip-szczepankiewicz 
Thank you for the information. With different names for both tags, we can keep the information for record. The potential issue is that the tag with new name won't used by `csa_header`. I wonder if it is a good idea to collapse the fields in both tags into `CSASeriesHeaderInfo`. But again, a testing file will be useful.
If you have concern for PHI, you may use `anonymize_dicm` in the package to modify one dicom file showing the issue, and then share with me.

**Comment by neurolabusc** [comment]
@xiangruili my dcm2niix only uses 0029_1020 which I believe is [standard](https://nipy.org/nibabel/dicom/siemens_csa.html). Even for ancient [B13 and B12](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage) images. I do not know of any exemplars where the `CSA Series Header Info` is stored in 0029_1120. Do you have a dataset that demonstrates this behavior?

**Comment by filip-szczepankiewicz** [comment]
@neurolabusc The non-standard location may not depend on scanner software age. The data I have seen this for is from a VE11C Prisma. What is strange is that data collected further back in time uses the standard tag, and now it is not. 

@xiangruili Merging the strings into one is a good idea! This solution would work just fine for me, but I cannot speak for the wider range of users.

I will try to get some phantom data and share it with you.

Be advised that patient data may be stored in the "alternative" CSASeriesHeaderInfo. At least I have seen patient names in there even if data was deidentified (not by dicm2nii framework).

**Comment by neurolabusc** [comment]
@filip-szczepankiewicz I have seen lots of E11C data from my site and others (e.g. [dcm_qa](https://github.com/neurolabusc/dcm_qa), [fmri](https://osf.io/q4d53/), [ASL](https://osf.io/td4bx/)) and have never seen this behavior. 

Is it possible that the private tags of your data have been [mangled by an AGFA or dcm4che PACS system](https://github.com/neurolabusc/dcm_qa_agfa)? Perhaps dicm2nii needs to be updated to support renaming of Private Data Element Tags. While renaming of private tags is legal, the intention was that it would be used to prevent naming conflicts. Unfortunately, dcm4che (and AGFA systems based on dcm4che) will use this feature when no conflicts exist, and will indeed use this feature to create conflicts. I suggest you determine the provenance of these images, and make sure to archive un-mangled data. While dicm2nii can be updated to handle this behavior, the opportunity for unintended consequences with other tools seems high. I would not consider mangled DICOMs of archival quality.

**Comment by neurolabusc** [comment]
@filip-szczepankiewicz I am aware that old versions of Siemens software did not initialize to zero the CSA headers. This could allow private information to leak into the fixed length portions of the header (e.g. null terminated strings were saved, but memory after the terminator would contain random data from prior memory writes). I reported this several years ago and believe it was fixed. Have you seen similar privacy issues with E11C data? If so, I strongly encourage you to work with your Siemens Research Collaboration Manager to have this resolved. This situation should be taken seriously.

**Comment by filip-szczepankiewicz** [comment]
Dear @neurolabusc and @xiangruili 
I have recieved an example dicom file for analysis (from @rstobbe). Please let me know how you would like me to send it.

As an aside, note that I am not at the site in question so I cannot answer for what processing has been applied. I am just working on header extraction for a custom pulse sequence that I am developing.

**Comment by neurolabusc** [comment]
Can you send archive the series as a .zip file and send a Box/DropBox/GoogleDrive link to my personal email (shown in my avatar).

**Comment by filip-szczepankiewicz** [comment]
Will do.

**Comment by neurolabusc** [comment]
@filip-szczepankiewicz in the sample you sent 0029_1120 is the [MedCom History Information](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary/Siemens.xml), and starts with the text MEDCOM HISTORY V1.1. Your file also contains a valid  CSA header (0029_1020). As I said, I have never seen the CSA information stored at 0029_1120. Perhaps @xiangruili saw some mangled files that led him to assume that CSA information could also be stored at 0029_1120, though I have never seen that behavior.

**Comment by xiangruili** [comment]
I don't remember when and why I also set 0029_1120 as CSASeriesHeaderInfo. I just updated it as MedComHistoryInformation. It seems there is no need to combine it with CSASeriesHeaderInfo. Thanks all for sorting this out.

**Comment by filip-szczepankiewicz** [comment]
@neurolabusc and @xiangruili 

OK... it all makes sense!

Just to clarify, and to make sure that im on the right page. The CSASeries info has always been at 0029_1020, but could later be overwritten by the content of 0029_1120 if it was populated (replacing the CSA with MedCom history).

Thank you both for the support! I will pull the new version and work on from there!
