### ISSUE TITLE
unicode2native() generates error for empty input

### ISSUE THREAD

**Issue by neurolabusc** [xiangruili/dicm2nii#37]
I believe [line 425 of nii_tool.m](https://github.com/xiangruili/dicm2nii/blob/5d8dcb822a0ed32f3d317a229704136ee52d35e4/nii_tool.m#L425) should be changed from

```
if strcmp(C0{i,3}, 'char')
```
to read
```
if (strcmp(C0{i,3}, 'char') && (~isempty(val)))
```
Without this modification, empty fields will generate the error:
```
Error using unicode2native
First argument must be a text scalar.
```

Example datasets which exhibit this issue are the Canon Enhanced scans Clement Debacker recently sent you.

**Comment by xiangruili** [comment]
@neurolabusc Thank you for the catching the error. I think it is fixed now.
