### ISSUE TITLE
Rotation of DTI data

### ISSUE THREAD

**Issue by neurolabusc** [xiangruili/dicm2nii#38]
I would suggest changing [dicm2nii.m](https://github.com/xiangruili/dicm2nii/blob/54519e4bd57e1fc403cfb95da9fb740c9f9d4965/dicm2nii.m#L1076) from

```
if (strcmp(tryGetField(s, 'MRAcquisitionType', ''), '3D') || s.isDTI) && ...
```
to read
```
if (strcmp(tryGetField(s, 'MRAcquisitionType', ''), '3D') ) && ...
```
The current release of dicm2nii will losslessly reslice coronal or sagittal to DTI data to the axial plane. It correctly updates the NIfTI [dim_info](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) and rotates the b-vectors appropriately. However, the current FSL tools eddy and topup ignore the dim_info field and assumes that the NIfTI k-dimension (slices as stored on disk) represents the acquisition slice order. You may want to make a feature request to the [FSL developers](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=fsl) to fully support the NIfTI standard. In the mean time, I think retaining the slice order is a wise idea. My sense is that coronal and sagittal DTI acquisitions are very rare in humans, so this is a rare corner case.

**Comment by xiangruili** [comment]
Done. Thanks @neurolabusc
