### ISSUE TITLE
Switch to force enable bids conversion GUI

### ISSUE THREAD

**Issue by ddwagner** [xiangruili/dicm2nii#50]
This is the opposite of this [closed issue](https://github.com/xiangruili/dicm2nii/issues/40). It would be convenient for users if there was a switch or setting to force the BIDS gui to be enabled for the current conversion. We've run into a situation were we initially skipped a scan that we now want to convert but as dicm2nii stores our preferences for that scan it's... tricky... to change it to something else. I understand we can investigate the various modality table preferences and potentially delete the offending one. However, it would be much easier for users (especially one's less familiar with matlab's preferences) if there was a simple switch that allowed us to force the GUI, make the change, and now that's the new preference going forward. 

It looks like line 698 might be the spot? 
` ~all(Lia) || all(toSkip) || numel(uniqueNames)<sum(~toSkip) `

Simply adding a switch like bidsforceGUI = true
` ~all(Lia) || all(toSkip) || numel(uniqueNames)<sum(~toSkip) || bidsforceGUI`

would that be something worth doing? Or maybe some other solution?

**Comment by ddwagner** [comment]
FYI, I have it working so I could submit a pull request if you'd like, though I figured you might do a better job or have some particular variable naming scheme in mind.

**Comment by xiangruili** [comment]
@ddwagner I am trying to do a little more than forcing the BIDS GUI on. The latest commit also allows to force GUI off (not a good idea though). Currently, this preference is accessible only from command line.

    setpref('dicm2nii_gui_para', 'bidsForceGUI', true); % force GUI on
    setpref('dicm2nii_gui_para', 'bidsForceGUI', false); % force GUI off
    setpref('dicm2nii_gui_para', 'bidsForceGUI', []); % default behavior, auto on or off

Let me know if you have better idea. Thanks.

**Comment by ddwagner** [comment]
Forgot to respond. I think that works well enough. But it would also be easy to add a switch to the script itself, that way it could be run without users (especially novices) having to fiddle with preferences and remember to reset them after.  

For example, add bidsGUI to dicm2nii.m and set it it's default to false. Then add it to line 698 as above. That way the default behavior is same but if the user sets it to True then the gui will open on this particular conversion regardless of any saved preferences for the bids table.  I think the issue I see is people forgetting to set the preferences back and teaching students what the preferences even are!
