### ISSUE TITLE
DICOMs anonymized with anonymize_dicm.m no longer convertivble to BIDS

### ISSUE THREAD

**Issue by ChristophWittkamp** [xiangruili/dicm2nii#51]
Calling dicm2nii on a folder with anonymized data leads to following error messeages:

Unrecognized field name "bytes".

Error in dicm_hdr>get_nFrames (line 559)
    elseif all(isfield(s, {'Columns' 'Rows' 'BitsAllocated'})) && p.bytes<4294967295

Error in dicm_hdr (line 310)
        p = get_nFrames(s, p, b8); % only make code here cleaner

Error in dicm2nii (line 293)
    [hh{k}, errStr{k}, dict] = dicm_hdr(fnames{k}, dict);

The function is called as: dicm2nii('anondir, targetdir, 'bids');
with anondir beeing a folder with the anonymized DICOMs.

The source of the issue seems to be in the script dicm_hdr.m but I could not figuere out a solution.

**Comment by xiangruili** [comment]
@ChristophWittkamp 
It is very unlikely that anonymize_dicm.m causes this problem, since it touches ONLY PatientName. Are the files also touched by other 3rd party software? If you can identity which dicom file gives the error, you may share the file with me, so I can take a look. Thanks.

**Comment by ChristophWittkamp** [comment]
Calling dicm2nii on the not anonymized dicom files works as normally. The functions are called from a Matlab script (2021a) as in the following quote:

```
[Short_ID] = deal(answer{:}); % all input variables are strings

subfolders = DirStruct(subdirects);
subFolderNames = {subfolders(3:end).name};
substruct.counter = {};

for k = 1 : length(subFolderNames)
    anonymize_dicm_CW(subFolderNames{k}, anondir, Short_ID);	 
end


%% Transform DICOM to nifti in BIDS format

dicm2nii(anondir, targetdir, 'bids');

```
s

**Comment by ChristophWittkamp** [comment]
It seems to be problem with the Siemens Scanner writing important information into private fields.
