### ISSUE TITLE
未定义与 'javax.swing.JTextField' 类型的输入参数相对应的函数 'java_dnd'

### ISSUE THREAD

**Issue by Roger1219** [xiangruili/dicm2nii#52]
你好，我在matlab r2018b使用DICM2nii工具
在图形界面下，输入，包含多个brik和head的文件，
然后报错如下，请问如何解决。谢谢！
未定义与 'javax.swing.JTextField' 类型的输入参数相对应的函数 'java_dnd'。
Xiangrui Li's dicm2nii.m 20191130 (feedback to xiangrui.li@gmail.com)
未定义函数或变量 'dicm_dict'。

出错 dicm2nii (line 287)
dict = dicm_dict('SIEMENS', flds); % dicm_hdr will update vendor if needed

出错 dicm2nii>gui_callback (line 1875)
        dicm2nii(src, dst, rstFmt);
 
计算 UIControl Callback 时出错。

**Comment by xiangruili** [comment]
I seems you downloaded part of the package. Download all files, and give it a try.

**Comment by Roger1219** [comment]
ok, thanks a lot.

xiangruili ***@***.***> 于2022年3月18日周五 11:22写道：
