### ISSUE TITLE
Unknown data type spectroscopy data XA30

### ISSUE THREAD

**Issue by NeuroimagingOL** [xiangruili/dicm2nii#68]
Dear all,

we just switched from VE11C to XA30. I used dicm2nii to convert all our datasets. In one of the studies we are using spectrocopy using HERMES sequence. In the previous version, the spectroscopy data was just ignored by dicm2nii, which is fine, because I use another software to convert the data as I do not need the dicoms. Nevertheless, since the upgrade to XA30 dicm2nii says "unknown data type" and stops further conversion. How can I just ignore the "unknown data types"?

Best regards,
Tina

**Comment by xiangruili** [comment]
@NeuroimagingOL 
It seems the error is in dicm_img.m. If you don't mind, you can share a file with me, so I may take care of this type files, either convert it, or skip it without error. I would appreciate if you can share one file for each of the older version and new version.

**Comment by NeuroimagingOL** [comment]
Dear @xiangruili,

thanks a lot for your fast reply. I attached both filetypes. The ones which I used in VE11C and the ones which are now measured in XA30. For me it is not necessary to convert them, because we use the raw twix data anyway. I use your code to convert all the other measures and upload the twix data with another programm. If would be sufficient just to skip them without stopping the script.

Thanks a lot in advance.
Tina

[github_example.zip](https://github.com/user-attachments/files/16687220/github_example.zip)

**Comment by neurolabusc** [comment]
@NeuroimagingOL for spectroscopy data, I would recommend you use [spec2nii](https://github.com/wtclarke/spec2nii) which is designed for this modality.

**Comment by NeuroimagingOL** [comment]
Thanks a lot for your advice, I did not know this tool so far. However, we are using Osprey for data analysis which directly uses the raw twix data as input, thus nothing needs to be converted from our side. The issue just came from the fact that we have functional, structural and spectroscopy data in the dicom files intermixed which leads dicm2nii to crash.

**Comment by xiangruili** [comment]
dicm2nii.m is just updated. It should convert XA30 SPEC data now.
The VE11 SPEC data are still skipped, since those are not dicom compliant at all. I think those are some versions during development, so I am not going to spend time on it.

**Comment by NeuroimagingOL** [comment]
Thanks a lot!
