### ISSUE TITLE
Issue with folder named 'Dicom' in the matlab path

### ISSUE THREAD

**Issue by julienbesle** [xiangruili/dicm2nii#7]
Hi Xiangrui,

I came across a bug in the very specific specific situation where a folder in the path is named 'dicom' and I ask dicm2nii to convert a dicom folder from the folder containing it.

for instance, if I call dicm2nii like this:

`dicm2nii('dicom/','.')`

I get the following error message:

`No valid files found:

Unknown file type: C:\Users\julien\Documents\matlab\mrToolsGit\mrUtilities\File\Dicom\readdicomheader.m
.`

This is because of the following line in dicm2nii, on line 458:
`dcmFolder = fullfile(getfield(what(dcmFolder), 'path'));`

what(dcmFolder) returns the path of the above function, instead of returning the path of the dicom folder in which the files to convert are located.
I don't get the error if I give the full path:
`dicm2nii('C:\Users\julien\Documents\data\Scanner\Olivier_diffusion\DICOM','.')`

**Comment by xiangruili** [comment]
Thanks for reporting the issue. Function `what` may give some problem. Now I include a function `fullpath` to try to get the full path if it is relative. It should be fixed.
