### ISSUE TITLE
i want to turn the sliced  dicom file into jpeg

### ISSUE THREAD

**Issue by PanPan0210** [xiangruili/dicm2nii#9]
I'm not going to do that,

**Comment by xiangruili** [comment]
If you are trying to save a dicom image into jpeg, you can do that by matlab `imwrite`. 

img = dicm_img('myDicomFile.dcm'); % read image using dicm2nii tool or
% img = dicomread('myDicomFile.dcm'); % if you have Image Processing Toolbox

img = single(img); % dicom img is often UINT16
img = img / max(img(:)); % you may choose a fixed value to normalize the img

imwrite(img, 'myJpegFile.jpg');  % save as jpeg file

**Comment by PanPan0210** [comment]
Yes, you can do this for individual dicom images, but not for 3D images.

my dicom file has 318 slices and it is a 3D picture ,also i want get its coronal
Sagittal plane and  Cross section

**Comment by xiangruili** [comment]
@PanPan0210 
Do you really want to get jpeg for all sag/cor/tra slices? That will be thousands of files. I would think you can use `nii_viewer` to view the image, and choose to save the interested view as jpeg. 

If you do want one file per slice, you can do something like:

    nii = nii_tool('load', 'my_3D_NiftiFile.nii.gz'); % load nii file
    for i = 1:nii.hdr.dim(4) % 3rd dim, typically axial slices
        img = single(nii.img(:,:,i)) / nii.hdr.glmax; % normalize by max value
        imwrite(img, sprintf('slice_%03g.jpg', i)); % one file each slice
    end
 
Then you can loop through other two dim to save sag/cor slices.
